server:
  port: 8888
 #端口

spring:
  # 数据库链接配置
  datasource:
    url:  jdbc:mysql://localhost:3306/pet_science?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 链接池
    type: com.alibaba.druid.pool.DruidDataSource

  # 邮箱配置
  mail:
    host: smtp.qq.com
    port: 465
    username: 3257249392@qq.com  # 发件人邮箱
    password: ukebuwtyzmdjdaai   # 授权码
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true

  servlet:
    multipart:
      #上传单个文件的最大值
      max-file-size: 10MB
      #单次请求中, 上传的所有文件总大小最大值
      max-request-size: 100MB
#    druid:
#      # 链接池初始化大小
#      initial-size: 8
#      # 最大活跃数
#      max-active: 16
#      # 最小空闲数
#      min-idle: 1
#      # 最大等待时间
#      max-wait: 60000
upload:
  path: C:/Users/zhouyu/Desktop/Project/pet-science-backend/src/main/resources/statics/images/userAvatar
  url: /statics/images/userAvatar
## mybatis配置
mybatis:
  #  配置mapper路径
  mapper-locations: "classpath:mybatis/mapper/*Mapper.xml"
  #  配置model包路径
  type-aliases-package: "com.pet_science.pojo"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
#  mybatis框架配置文件，对mybatis的生命周期起作用
#  config-location: "classpath:mybatis/mybatisConfig.xml"
#  check-config-location: true


